---
title: "Projekt analiza danych"
author: "Wojciech Mikołajczyk"
date: "December 2, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Wykorzystane biblioteki
```{r load libraries, message=FALSE}
library(dplyr)
library(ggplot2)
library(reshape2)
library(caret)
```

### Wczytanie danych z pliku
```{r load data, cache=TRUE}
data <- read.csv('elektrownie.csv')
```

### Krótkie podsumowanie danych w zbiorze
##### Podstawowe statystyki
```{r short datasummary}
summary(data)
```
##### Liczba wierszy danych
```{r}
nrow(data)
```

##### Korelacja między zmiennymi
Odfiltrowanie daty, aby zostały same numeryczne wartości
Macierz korelacji jest symetryczna, więc dla czytelności usuwamy górny trójkąt
```{r}
data <- data[, !(names(data) %in% 'data')]
correlations <- round(cor(data), 2)
correlations[upper.tri(correlations)] <- NA
correlations_melt <- melt(correlations, na.rm = TRUE)

ggplot(data = correlations_melt, aes(Var1, Var2, fill = value)) + 
  geom_tile(color = "white") + 
  scale_fill_gradient2(low="blue", mid="white", high="red", midpoint=0, limit=c(-1,1)) + 
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 70, size = 8, vjust = 1, hjust = 1)) +
  coord_fixed()
```

